<Project>
  <PropertyGroup>
    <Version>0.2.0</Version>
    <Company>QuantaTray contributors</Company>
    <Product>QuantaTray</Product>
    <Copyright>Copyright © 2026 QuantaTray contributors</Copyright>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
